import type { BusinessRequest } from "@/lib/contracts";

export const DEMO_REQUESTS: BusinessRequest[] = [
  {
    request_id: "REQ-001",
    received_at: "2026-07-10",
    category: "契約",
    customer: "ABC商事",
    description: "契約内容を確認したい",
    urgency: "medium",
    status: "open",
    due_date: "2026-07-18",
  },
  {
    request_id: "REQ-002",
    received_at: "2026-07-11",
    category: "障害",
    customer: "XYZ株式会社",
    description: "サービスにログインできない",
    urgency: "high",
    status: "open",
    due_date: "2026-07-12",
  },
  {
    request_id: "REQ-003",
    received_at: "2026-07-12",
    category: "請求",
    customer: "DEF合同会社",
    description: "請求金額が異なる",
    urgency: "high",
    status: "open",
    due_date: "2026-07-14",
  },
  {
    request_id: "REQ-004",
    received_at: "2026-07-12",
    category: "総務",
    customer: "GHI株式会社",
    description: "入館証の再発行を依頼したい",
    urgency: "low",
    status: "closed",
    due_date: "2026-07-16",
  },
  {
    request_id: "REQ-005",
    received_at: "2026-07-13",
    category: "障害",
    customer: "JKL商事",
    description: "連携APIでエラーが発生する",
    urgency: "high",
    status: "in_progress",
    due_date: "2026-07-13",
  },
  {
    request_id: "REQ-006",
    received_at: "2026-07-13",
    category: "契約",
    customer: "MNO株式会社",
    description: "NDAの確認を依頼したい",
    urgency: "medium",
    status: "open",
    due_date: "2026-07-20",
  },
  {
    request_id: "REQ-007",
    received_at: "2026-07-09",
    category: "注文",
    customer: "PQRストア",
    description: "配送先を変更したい",
    urgency: "medium",
    status: "closed",
    due_date: "2026-07-11",
  },
  {
    request_id: "REQ-008",
    received_at: "2026-07-13",
    category: "申請",
    customer: "社内利用者A",
    description: "業務アカウントを発行してほしい",
    urgency: "high",
    status: "open",
    due_date: "2026-07-13",
  },
];
